import type { League, Club } from "@/types";

function mk(
  country: string,
  league: string,
  countryCode: string,
  raw: Array<[string, string, number]>, // [name, slug, tier]
): Club[] {
  return raw.map(([name, slug, tier]) => ({
    id: `${countryCode}-${slug}`,
    name,
    shortName: name,
    country,
    league,
    tier,
    logoSlug: slug,
  }));
}

export const LEAGUES: Record<string, League> = {
  AR: {
    id: "AR",
    country: "Argentina",
    countryCode: "AR",
    name: "Liga Profesional",
    confederation: "CONMEBOL",
    logoSlug: null,
    clubs: mk("Argentina", "Liga Profesional", "AR", [
      ["Boca Juniors", "boca-juniors", 1],
      ["River Plate", "river-plate", 1],
      ["Racing Club", "racing-club", 2],
      ["Independiente", "independiente", 2],
      ["San Lorenzo", "san-lorenzo-de-almagro", 2],
      ["Estudiantes LP", "estudiantes-de-la-plata", 2],
      ["Vélez Sarsfield", "velez-sarsfield", 2],
      ["Newell's Old Boys", "newells-old-boys", 3],
      ["Rosario Central", "rosario-central", 3],
      ["Lanús", "lanus", 3],
      ["Talleres", "talleres", 3],
      ["Huracán", "ca-huracan", 3],
      ["Belgrano", "belgrano", 3],
      ["Tigre", "tigre", 4],
      ["Banfield", "banfield", 4],
      ["Argentinos Juniors", "argeninos-juniors", 4],
      ["Defensa y Justicia", "defensa-y-justicia", 4],
      ["Instituto", "instituto-cordoba", 4],
      ["Central Córdoba", "central-cordoba", 4],
      ["Unión", "union", 4],
      ["Sarmiento", "sarmiento", 4],
      ["Aldosivi", "aldosivi", 4],
      ["Barracas Central", "barracas-central", 4],
      ["Platense", "club-atletico-platanense", 4],
      ["Atlético Tucumán", "atletico-tucuman", 4],
      ["Estudiantes RC", "estudiantes-de-rio-cuarto", 4],
      ["Independiente Rivadavia", "independiente-rivadavia", 4],
      ["Deportivo Riestra", "deportivo-riestra", 4],
      ["Gimnasia LP", "gimnasia-lp", 4],
      ["Gimnasia y Esgrima", "gimnasia-y-esgrima", 4],
    ]),
  },
  BR: {
    id: "BR",
    country: "Brasil",
    countryCode: "BR",
    name: "Brasileirão",
    confederation: "CONMEBOL",
    logoSlug: null,
    clubs: mk("Brasil", "Brasileirão", "BR", [
      ["Flamengo", "flamengo", 1],
      ["Palmeiras", "palmeiras", 1],
      ["São Paulo", "sao-paulo", 1],
      ["Corinthians", "corinthians", 2],
      ["Fluminense", "fluminense", 2],
      ["Botafogo", "botafogo", 2],
      ["Atlético Mineiro", "atletico-mineiro", 2],
      ["Grêmio", "gremio", 2],
      ["Internacional", "internacional", 2],
      ["Santos", "santos", 3],
      ["Cruzeiro", "cruzeiro", 3],
      ["Vasco da Gama", "vasco-da-gama", 3],
      ["Athletico Paranaense", "athletico-paranaense", 3],
      ["Bahia", "bahia", 3],
      ["RB Bragantino", "rb-bragantino", 3],
      ["Vitória", "vitoria", 4],
      ["Mirassol", "mirassol", 4],
      ["Coritiba", "coritiba", 4],
      ["Chapecoense", "chapecoense", 4],
      ["Clube do Remo", "clube-do-remo", 4],
    ]),
  },
  ES: {
    id: "ES",
    country: "España",
    countryCode: "ES",
    name: "LaLiga",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("España", "LaLiga", "ES", [
      ["Real Madrid", "real-madrid", 1],
      ["FC Barcelona", "barcelona", 1],
      ["Atlético Madrid", "atletico-madrid", 1],
      ["Athletic Club", "athletic-club", 2],
      ["Real Sociedad", "real-sociedad", 2],
      ["Real Betis", "real-betis", 2],
      ["Villarreal", "villarreal", 2],
      ["Valencia", "valencia", 2],
      ["Sevilla", "sevilla", 2],
      ["Girona", "girona", 3],
      ["Osasuna", "osasuna", 3],
      ["Celta Vigo", "celta", 3],
      ["Rayo Vallecano", "rayo-vallecano", 3],
      ["Mallorca", "mallorca", 4],
      ["Getafe", "getafe", 4],
      ["Espanyol", "espanyol", 4],
      ["Levante", "levante", 4],
      ["Elche", "elche", 4],
      ["Real Oviedo", "oviedo", 4],
      ["Deportivo", "deportivo", 4],
    ]),
  },
  EN: {
    id: "EN",
    country: "Inglaterra",
    countryCode: "EN",
    name: "Premier League",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Inglaterra", "Premier League", "EN", [
      ["Manchester City", "manchester-city", 1],
      ["Arsenal", "arsenal", 1],
      ["Liverpool", "liverpool", 1],
      ["Manchester United", "manchester-united", 1],
      ["Chelsea", "chelsea", 1],
      ["Tottenham", "tottenham", 2],
      ["Newcastle United", "newcastle", 2],
      ["Aston Villa", "aston-villa", 2],
      ["Brighton", "brighton", 3],
      ["West Ham", "west-ham", 3],
      ["Crystal Palace", "crystal-palace", 3],
      ["Brentford", "brentford", 3],
      ["Nottingham Forest", "nottingham-forest", 3],
      ["Wolves", "wolves", 4],
      ["Fulham", "fulham", 4],
      ["Everton", "everton", 4],
      ["Bournemouth", "bournemouth", 4],
      ["Leeds United", "leeds-united", 4],
      ["Sunderland", "sunderland", 4],
      ["Burnley", "burnley", 4],
    ]),
  },
  SC: {
    id: "SC",
    country: "Escocia",
    countryCode: "SC",
    name: "Scottish Premiership",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Escocia", "Scottish Premiership", "SC", [
      ["Celtic", "celtic", 1],
      ["Rangers", "rangers", 1],
      ["Aberdeen", "aberdeen", 2],
      ["Hearts", "hearts", 2],
      ["Hibernian", "hibernian", 2],
      ["Dundee United", "dundee-united", 3],
      ["Motherwell", "motherwell", 3],
      ["St Mirren", "st-mirren", 3],
      ["Kilmarnock", "kilmarnock", 4],
      ["Dundee", "dundee", 4],
      ["Falkirk", "falkirk", 4],
      ["Livingston", "livingston", 4],
    ]),
  },
  IT: {
    id: "IT",
    country: "Italia",
    countryCode: "IT",
    name: "Serie A",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Italia", "Serie A", "IT", [
      ["Inter", "inter", 1],
      ["Juventus", "juventus", 1],
      ["AC Milan", "milan", 1],
      ["Napoli", "napoli", 1],
      ["Roma", "roma", 2],
      ["Lazio", "lazio", 2],
      ["Atalanta", "atalanta", 2],
      ["Fiorentina", "fiorentina", 2],
      ["Bologna", "bologna", 3],
      ["Torino", "torino", 3],
      ["Udinese", "udinese", 3],
      ["Genoa", "genoa", 4],
      ["Como", "como-1907", 4],
      ["Sassuolo", "sassuolo", 4],
      ["Hellas Verona", "verona", 4],
      ["Parma", "parma", 4],
      ["Lecce", "lecce", 4],
      ["Cagliari", "cagliari", 4],
      ["Pisa", "pisa", 4],
      ["Cremonese", "cremonese", 4],
    ]),
  },
  FR: {
    id: "FR",
    country: "Francia",
    countryCode: "FR",
    name: "Ligue 1",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Francia", "Ligue 1", "FR", [
      ["Paris Saint-Germain", "paris-saint-germain", 1],
      ["Marseille", "marseille", 2],
      ["Monaco", "as-monaco", 2],
      ["Lyon", "lyon", 2],
      ["Lille", "lille", 2],
      ["Nice", "nice", 2],
      ["Lens", "rc-lens", 3],
      ["Rennes", "rennes", 3],
      ["Strasbourg", "rc-strasbourg-alsace", 3],
      ["Nantes", "nantes", 4],
      ["Toulouse", "toulouse", 4],
      ["Brest", "brest", 4],
      ["Auxerre", "auxerre", 4],
      ["Angers", "angers", 4],
      ["Lorient", "lorient", 4],
      ["Le Havre", "le-havre-ac", 4],
      ["Metz", "fc-metz", 4],
      ["Paris FC", "paris-fc", 4],
    ]),
  },
  DE: {
    id: "DE",
    country: "Alemania",
    countryCode: "DE",
    name: "Bundesliga",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Alemania", "Bundesliga", "DE", [
      ["Bayern München", "bayern-munchen", 1],
      ["Bayer Leverkusen", "bayer-leverkusen", 1],
      ["Borussia Dortmund", "borussia-dortmund", 1],
      ["RB Leipzig", "rb-leipzig", 2],
      ["VfB Stuttgart", "vfb-stuttgart", 2],
      ["Eintracht Frankfurt", "eintracht-frankfurt", 2],
      ["Wolfsburg", "wolfsburg", 3],
      ["Borussia M'gladbach", "borussia-monchengladbach", 3],
      ["Hoffenheim", "hoffenheim", 3],
      ["Werder Bremen", "werder-bremen", 3],
      ["Union Berlin", "union-berlin", 3],
      ["Freiburg", "freiburg", 3],
      ["Hamburger SV", "hamburger-sv", 3],
      ["Mainz 05", "mainz-05", 4],
      ["FC Augsburg", "augsburg", 4],
      ["St. Pauli", "st-pauli", 4],
      ["FC Köln", "koln", 4],
      ["Heidenheim", "fc-heidenheim", 4],
    ]),
  },
  PT: {
    id: "PT",
    country: "Portugal",
    countryCode: "PT",
    name: "Primeira Liga",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Portugal", "Primeira Liga", "PT", [
      ["Benfica", "benfica", 1],
      ["Porto", "fc-porto", 1],
      ["Sporting CP", "sporting-cp", 1],
      ["Braga", "sc-braga", 2],
      ["Vitória Guimarães", "vitoria-de-guimaraes", 3],
      ["Famalicão", "famalicao", 4],
      ["Casa Pia", "casa-pia-ac", 4],
      ["Rio Ave", "rio-ave", 4],
      ["Santa Clara", "santa-clara", 4],
      ["Estoril", "estoril", 4],
      ["Arouca", "arouca", 4],
      ["Gil Vicente", "gil-vicente", 4],
      ["Moreirense", "moreirense", 4],
      ["Nacional", "nacional-da-madeira", 4],
      ["Tondela", "tondela", 4],
      ["Estrela Amadora", "estrela-da-amadora", 4],
      ["AVS", "avs-futebol-sad", 4],
      ["Alverca", "alverca", 4],
    ]),
  },
  NL: {
    id: "NL",
    country: "Países Bajos",
    countryCode: "NL",
    name: "Eredivisie",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Países Bajos", "Eredivisie", "NL", [
      ["Ajax", "ajax", 1],
      ["PSV", "psv", 1],
      ["Feyenoord", "feyenoord", 1],
      ["AZ Alkmaar", "az-alkmaar", 2],
      ["Twente", "twente", 3],
      ["Utrecht", "fc-utrecht", 3],
      ["Heerenveen", "sc-heerenveen", 3],
      ["Sparta Rotterdam", "sparta-rotterdam", 4],
      ["NEC Nijmegen", "nec-nijmegen", 4],
      ["FC Groningen", "fc-groningen", 4],
      ["NAC Breda", "nac-breda", 4],
      ["Go Ahead Eagles", "go-ahead-eagles", 4],
      ["Heracles", "heracles-almelo", 4],
      ["Excelsior", "excelsior-rotterdam", 4],
      ["PEC Zwolle", "pec-zwolle", 4],
      ["Fortuna Sittard", "fortuna-sittard", 4],
      ["Volendam", "volendam", 4],
      ["Telstar", "telstar", 4],
    ]),
  },
  BE: {
    id: "BE",
    country: "Bélgica",
    countryCode: "BE",
    name: "Pro League",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Bélgica", "Pro League", "BE", [
      ["Club Brugge", "club-brugge", 1],
      ["Anderlecht", "anderlecht", 2],
      ["Genk", "genk", 2],
      ["Antwerp", "antwerp", 2],
      ["Gent", "gent", 2],
      ["Union SG", "union-saint-gilloise", 2],
      ["Standard Liège", "standard-liege", 3],
      ["Mechelen", "mechelen", 3],
      ["Cercle Brugge", "cercle-brugge", 4],
      ["Charleroi", "charleroi", 4],
      ["OH Leuven", "oud-heverlee-leuven", 4],
      ["Westerlo", "westerlo", 4],
      ["Sint-Truiden", "sint-truidense", 4],
      ["Zulte Waregem", "zulte-waregem", 4],
      ["Dender", "fcv-dender-eh", 4],
      ["RAAL La Louvière", "raal-la-louviere", 4],
    ]),
  },
  TR: {
    id: "TR",
    country: "Turquía",
    countryCode: "TR",
    name: "Süper Lig",
    confederation: "UEFA",
    logoSlug: null,
    clubs: mk("Turquía", "Süper Lig", "TR", [
      ["Galatasaray", "galatasaray", 1],
      ["Fenerbahçe", "fenerbahce", 1],
      ["Beşiktaş", "besiktas", 1],
      ["Trabzonspor", "trabzonspor", 2],
      ["Başakşehir", "basaksehir", 3],
      ["Konyaspor", "konyaspor", 3],
      ["Samsunspor", "samsunspor", 3],
      ["Alanyaspor", "alanyaspor", 4],
      ["Antalyaspor", "antalyaspor", 4],
      ["Kasımpaşa", "kasimpasa", 4],
      ["Gaziantep", "gaziantep", 4],
      ["Eyüpspor", "eyupspor", 4],
      ["Rizespor", "rizespor", 4],
      ["Kayserispor", "kayserispor", 4],
      ["Kocaelispor", "kocaelispor", 4],
      ["Karagümrük", "fatih-karagumruk", 4],
      ["Göztepe", "goztepe-izmir", 4],
      ["Gençlerbirliği", "genclerbirligi", 4],
    ]),
  },
  US: {
    id: "US",
    country: "Estados Unidos",
    countryCode: "US",
    name: "MLS",
    confederation: "CONCACAF",
    logoSlug: null,
    clubs: mk("Estados Unidos", "MLS", "US", [
      ["Inter Miami", "inter-miami-cf", 1],
      ["LAFC", "los-angeles-fc", 1],
      ["LA Galaxy", "la-galaxy", 2],
      ["Seattle Sounders", "seattle-sounders-fc", 2],
      ["Atlanta United", "atlanta-united", 2],
      ["New York City FC", "new-york-city-fc", 2],
      ["NY Red Bulls", "new-york-red-bulls", 3],
      ["Portland Timbers", "portland-timbers", 3],
      ["Toronto FC", "toronto-fc", 3],
      ["Columbus Crew", "columbus-crew", 2],
      ["FC Cincinnati", "fc-cincinnati", 3],
      ["Philadelphia Union", "philadelphia-union", 3],
      ["Nashville SC", "nashville-sc", 3],
      ["St. Louis City", "st-louis-city-sc", 3],
      ["San Diego FC", "san-diego-fc", 3],
      ["Charlotte FC", "charlotte-fc", 4],
      ["CF Montreal", "cf-montreal", 4],
      ["Chicago Fire", "chicago-fire-fc", 4],
      ["Colorado Rapids", "colorado-rapids", 4],
      ["DC United", "dc-united", 4],
      ["FC Dallas", "fc-dallas", 4],
      ["Houston Dynamo", "houston-dynamo", 4],
      ["Minnesota United", "minnesota-united-fc", 4],
      ["New England", "new-england-revolution", 4],
      ["Orlando City", "orlando-city", 4],
      ["Real Salt Lake", "real-salt-lake", 4],
      ["San Jose Earthquakes", "san-jose-earthquakes", 4],
      ["Sporting Kansas City", "sporting-kansas-city", 4],
      ["Vancouver Whitecaps", "vancouver-whitecaps-fc", 4],
      ["Austin FC", "austins-fc", 4],
    ]),
  },
  SA: {
    id: "SA",
    country: "Arabia Saudita",
    countryCode: "SA",
    name: "Saudi Pro League",
    confederation: "AFC",
    logoSlug: null,
    clubs: mk("Arabia Saudita", "Saudi Pro League", "SA", [
      ["Al-Hilal", "al-hilal", 1],
      ["Al-Nassr", "al-nassr", 1],
      ["Al-Ittihad", "al-ittihad", 1],
      ["Al-Ahli", "al-ahli", 1],
      ["Al-Qadsiah", "al-qadsiah", 2],
      ["Al-Shabab", "al-shabab", 2],
      ["Al-Ettifaq", "al-ettifaq", 2],
      ["Al-Taawoun", "al-taawoun", 3],
      ["Al-Fateh", "al-fateh", 3],
      ["Al-Riyadh", "al-riyadh", 4],
      ["Al-Khaleej", "al-khaleej", 4],
      ["Al-Fayha", "al-fayha", 4],
      ["Al-Okhdood", "al-okhdood", 4],
      ["Al-Kholood", "al-kholood", 4],
      ["Al-Najma", "al-najma", 4],
      ["Al-Hazem", "al-hazem", 4],
      ["Damac", "damac", 4],
      ["NEOM SC", "neom", 4],
    ]),
  },
};

export function getLeagueByCountry(code: string): League {
  const league = LEAGUES[code];
  if (!league) throw new Error(`No league for country: ${code}`);
  return league;
}

export function allClubs(): Club[] {
  return Object.values(LEAGUES).flatMap((l) => l.clubs);
}

export function clubById(id: string): Club | undefined {
  for (const l of Object.values(LEAGUES)) {
    const c = l.clubs.find((x) => x.id === id);
    if (c) return c;
  }
  return undefined;
}

export function leagueByName(name: string): League | undefined {
  return Object.values(LEAGUES).find((l) => l.name === name);
}
